## aforce

```{r, eval=TRUE, include=FALSE}
library(htmltools)
```

```{r, echo=FALSE}
div(
  class = "row",
  div(
    class = "col-md-3",
    img(src = "logo.png")
  ),
  div(
    class = "col-md-9",
    "3D Virtual Force Directed Graph in R."
  )
)
```

### Installation

```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("JohnCoene/aforce")
```

### Example

```{r, eval=TRUE}
library(aforce)

data("some_nodes")
data("some_links")

aForce$
  new(n_label = "label")$ # initialise
  nodes(some_nodes, id, val, color, label)$ # add nodes
  links(some_links, source, target)$ # add edges
  build( # build
    aframer::a_camera(
      `wasd-controls` = "fly: true; acceleration: 600",
      aframer::a_cursor(opacity = 0.5)
    ),
    aframer::a_sky(color="#4c4c4c")
  )$ 
  embed() # get embed tag
```

Click the link below for a full-screen version.

```{r, echo=FALSE}
tags$a(
  tags$i(class = "fa fa-lg fa-eye"),
  " Demo",
  href = "example.html",
  target = "_blank",
  class = "btn btn-lg btn-primary btn-blue"
)
```
